=== pralmeida/PDE-Trabalho1/guiao.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.pauloalmeida.org/guiao"
	xmlns:tns="http://www.pauloalmeida.org/guiao"
	elementFormDefault="qualified">
	<include schemaLocation=""></include>

	<element name="guiao">
	    <complexType>
	    	<sequence>
	    		<element name="cabecalho" maxOccurs="1" minOccurs="1">
	    			<complexType>
	    				<sequence>
	    					<element name="titulo" type="string"
	    						maxOccurs="1" minOccurs="1">
	    					</element>
	    					<element name="autores" maxOccurs="1"
	    						minOccurs="0">
	    						<complexType>
	    							<sequence>
	    								<element name="autor"
	    									maxOccurs="unbounded" minOccurs="1" type="string">
	    								</element>

	    							</sequence>
	    						</complexType>
	    					</element>
	    					<element name="data_publicacao"
	    						type="tns:data" maxOccurs="1" minOccurs="1">
	    					</element>
	    					<element name="personagens"
	    						type="tns:personagens" maxOccurs="1" minOccurs="1">
	    					</element>
	    					<element name="sinopse" type="string"
	    						maxOccurs="1" minOccurs="0">
	    					</element>
	    				</sequence>
	    			</complexType>
	    		</element>
	    		<choice maxOccurs="1" minOccurs="0">
	    			<element name="temporadas" type="string" maxOccurs="1" minOccurs="0"></element>
	    			<element name="episodios" type="string" maxOccurs="1" minOccurs="0"></element>
	    			<element name="partes" type="string" maxOccurs="1" minOccurs="0"></element>
	    			<element name="cenas" maxOccurs="1" minOccurs="0">
	    				<complexType>
	    					<sequence>
	    						<element name="cena"
	    							maxOccurs="unbounded" minOccurs="0">
	    							<complexType>
	    								<sequence>
	    									<element name="titulo"
	    										type="string" maxOccurs="1" minOccurs="1">
	    									</element>
	    									<element name="personagens"
	    										type="tns:personagens" maxOccurs="1" minOccurs="0">
	    									</element>
	    									<element name="sinopse"
	    										type="string" maxOccurs="1" minOccurs="0">
	    									</element>
	    									<element name="contexto"
	    										type="string" maxOccurs="1" minOccurs="1">
	    									</element>
	    									<element
	    										name="conteudo_cena" maxOccurs="1" minOccurs="1">
	    										<complexType mixed="true">
	    											<choice maxOccurs="unbounded" minOccurs="0">
	    												<element
	    													name="fala" maxOccurs="unbounded" minOccurs="0">
	    													<complexType
	    														mixed="true">
	    														<choice maxOccurs="unbounded" minOccurs="0">
	    															<element
	    																name="adereco" type="string">
	    															</element>
	    															<element
	    																name="comentario" type="string">
	    															</element>
	    														</choice>
	    														<attribute
	    															name="personagem" type="IDREF" use="required">
	    														</attribute>
	    													</complexType>
	    												</element>
	    												<element
	    													name="refere" maxOccurs="unbounded" minOccurs="0">
	    													<complexType>
	    														<simpleContent>
	    															<extension
	    																base="string">
	    																<attribute
	    																	name="personagem" type="IDREF" use="required">
	    																</attribute>
	    															</extension>
	    														</simpleContent>
	    													</complexType>
	    												</element>
	    												<element
	    													name="comentario" type="string" maxOccurs="unbounded" minOccurs="0">
	    												</element>
	    												<element
	    													name="adereco" type="string" maxOccurs="unbounded" minOccurs="0">
	    												</element>
	    											</choice>
	    										</complexType>
	    									</element>
	    								</sequence>
	    								<attribute name="id"
	    									type="ID">
	    								</attribute>
	    							</complexType>
	    						</element>
	    					</sequence>
	    				</complexType>
	    			</element>
	    		</choice>
	    	</sequence>
	    </complexType>
	</element>
	




	<complexType name="data">
		<sequence>
			<element name="ano" type="int"></element>
			<element name="mes" type="int"></element>
			<element name="dia" type="int"></element>
		</sequence>
	</complexType>

	<complexType name="personagens">
		<sequence>
			<element name="personagem" maxOccurs="unbounded"
				minOccurs="0">
				<complexType>
					<sequence>
						<element name="nome" type="string" maxOccurs="1"
							minOccurs="1">
						</element>
						<element name="descricao" type="string"
							maxOccurs="1" minOccurs="1">
						</element>
					</sequence>
					<attribute name="id" type="ID"></attribute>
				</complexType>
			</element>
		</sequence>
	</complexType>
</schema>

<!-- 
<!ELEMENT guiaoguiao (cabecalho, (temporadas|episodios|partes|cenas)?)>
<!ELEMENT cabecalho (titulo, autores?, data_publicacao, personagens, sinopse?)>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT autores (autor+)>
<!ELEMENT autor (#PCDATA)>
<!ELEMENT data_publicacao (ano, mes, dia)>
<!ELEMENT ano (#PCDATA)>
<!ELEMENT mes (#PCDATA)>
<!ELEMENT dia (#PCDATA)>
<!ELEMENT personagens (personagem*)>
<!ELEMENT personagem (nome, descricao)>
<!ATTLIST personagem id ID #REQUIRED>
<!ELEMENT identificador (#PCDATA)>
<!ELEMENT nome (#PCDATA)>
 -->

=== pralmeida/PDE-Trabalho1/Partes_XSD.xml
<?xml version="1.0"?>
<guiao
	xmlns="http://www.pauloalmeida.org/guiao"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.pauloalmeida.org/guiao guiao.xsd">
	<cabecalho>
		<titulo>Título do Filme</titulo>
		<autores>
			<autor>Autor 1</autor>
			<autor>Autor 2</autor>		
		</autores>
		<data_publicacao><ano>2013</ano><mes>03</mes><dia>12</dia></data_publicacao>
		<personagens>
			<personagem id="p1">
				<nome>Personagem 1</nome>
				<descricao>Personagem 1. Declarada no cabeçalho.</descricao>
			</personagem>
			<personagem id="p2">
				<nome>Personagem 2</nome>
				<descricao>Personagem 2. Declarada no cabeçalho.</descricao>
			</personagem>
		</personagens>
		<sinopse>Sinopse do guião no cabeçalho.</sinopse>
	</cabecalho>
	<partes>
		<parte id="parte1">
			<titulo>Primeira Parte. Só com título e sinopse.</titulo>
			<sinopse>Sinopse da parte 1 do episódio 2 da temporada 2.</sinopse>
		</parte>
		<parte id="parte2">
			<titulo>Parte 2. Com cenas.</titulo>
			<personagens>
				<personagem id="p4">
					<nome>Personagem 4. Declarada na parte 2</nome>
					<descricao>Descrição do personagem 4</descricao>
				</personagem>
				<personagem id="p3">
					<nome>Personagem 3</nome>
					<descricao>Personagem 3. Declarada na parte 2.</descricao>
				</personagem>
			</personagens>
			<cenas>
				<cena contexto="Contexto da cena 1.">
				    <fala personagem="p1">Vou te matar!</fala>
				    Enquanto diz isto pega na <adereco>pistola</adereco> e dispara.
				    <fala personagem="p2">Ahh, mataste-me...</fala>
				    E cai morto no chão.
				    <fala personagem="p3">123</fala>
					<!-- GENE HACKMAN (V.O.) - The world of investing can be a jungle. (COMO REPRESENTAR UMA VOICE OVER? CONSIDERA-SE UMA FALA? 2 tipos de falas: locução ou diálogo?) -->
				</cena>
				<cena contexto = "Absolute bedlam. 300 drunken STOCKBROKERS, most in their early 20s">
				    <fala personagem="p1">Vou te matar, personagem 2!</fala>
				    Enquanto diz isto o <refere personagem="p1">personagem 1</refere> pega na <adereco>pistola</adereco> e dispara.
				    <fala personagem="p2">Ahh, mataste-me...</fala>
				    E o <refere personagem="p2">personagem 2</refere> cai morto no chão.
				</cena>							
			</cenas>
		</parte>
	</partes>


</guiao>
