=== pralmeida/PDE-Trabalho1/guiao.dtd
<!ELEMENT guiao (cabecalho, cena+)>
<!ELEMENT cabecalho (titulo, autor+, data_publicacao, personagens, sinopse?)>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT autor (#PCDATA)>
<!ELEMENT data_publicacao (ano, mes, dia)>
<!ELEMENT ano (#PCDATA)>
<!ELEMENT mes (#PCDATA)>
<!ELEMENT dia (#PCDATA)>
<!ELEMENT personagens (personagem*)>
<!ELEMENT personagem (identificador, nome, descricao)>
<!ELEMENT identificador (#PCDATA)>
<!ELEMENT nome (#PCDATA)>
<!ELEMENT descricao (#PCDATA)>
<!ELEMENT sinopse (#PCDATA)>
<!ELEMENT cena (identificador, titulo, contexto, (fala|refere|comentario|adereco)*)>
<!ELEMENT contexto (#PCDATA)>
<!ELEMENT fala (#PCDATA)>
<!ELEMENT refere (#PCDATA)>
<!ELEMENT comentario (#PCDATA)>
<!ELEMENT adereco (#PCDATA)>

=== pralmeida/PDE-Trabalho1/Partes_DTD.xml
<?xml version="1.0"?>
<!DOCTYPE note SYSTEM "guiao.dtd">
<guiao>
	<cabecalho>
		<titulo>Título do Filme</titulo>
		<autores>
			<autor>Autor 1</autor>
			<autor>Autor 2</autor>		
		</autores>
		<data_publicacao><ano>2013</ano><mes>03</mes><dia>12</dia></data_publicacao>
		<personagens>
			<personagem id="p1">
				<nome>Personagem 1</nome>
				<descricao>Personagem 1. Declarada no cabeçalho.</descricao>
			</personagem>
			<personagem id="p2">
				<nome>Personagem 2</nome>
				<descricao>Personagem 2. Declarada no cabeçalho.</descricao>
			</personagem>
		</personagens>
		<sinopse>Sinopse do guião no cabeçalho.</sinopse>
	</cabecalho>
	<partes>
		<parte id="parte1">
			<titulo>Primeira Parte. Só com título e sinopse.</titulo>
			<sinopse>Sinopse da parte 1 do episódio 2 da temporada 2.</sinopse>
		</parte>
		<parte id="parte2">
			<titulo>Parte 2. Com cenas.</titulo>
			<personagens>
				<personagem id="p4">
					<nome>Personagem 4. Declarada na parte 2</nome>
					<descricao>Descrição do personagem 4</descricao>
				</personagem>
			</personagens>
			<cenas>
				<cena id="c1">
					<titulo>Título da Cena 1</titulo>
					<sinopse>Sinopse da Cena 1.</sinopse>
					<contexto>
						Contexto da cena 1.
					</contexto>
					<conteudo_cena>
					    <fala personagem="p1">Vou te matar!</fala>
					    Enquanto diz isto pega na <adereco>pistola</adereco> e dispara.
					    <fala personagem="p2">Ahh, mataste-me...</fala>
					    E cai morto no chão.
					    <fala personagem="p3">123</fala>
					</conteudo_cena>
					<!-- GENE HACKMAN (V.O.) - The world of investing can be a jungle. (COMO REPRESENTAR UMA VOICE OVER? CONSIDERA-SE UMA FALA? 2 tipos de falas: locução ou diálogo?) -->
				</cena>
				<cena id = "c2">
					<titulo>INT. STRATTON OAKMONT III - BULLPEN - DAY (FEB ‘95)</titulo>
					<personagens>
						<personagem id="p3">
							<nome>Personagem 3</nome>
							<descricao>Personagem 3. Declarada na cena 3.</descricao>
						</personagem>
					</personagens>
					<contexto>
						Absolute bedlam. 300 drunken STOCKBROKERS, most in their early 20s, chant wildly as JORDAN BELFORT, handsome, 30, stands beside a DWARF dressed in tights, cape &amp; helmet.
					</contexto>
					<conteudo_cena>
					    <fala personagem="p1">Vou te matar, personagem 2!</fala>
					    Enquanto diz isto o <refere personagem="p1">personagem 1</refere> pega na <adereco>pistola</adereco> e dispara.
					    <fala personagem="p2">Ahh, mataste-me...</fala>
					    E o <refere personagem="p2">personagem 2</refere> cai morto no chão.
					</conteudo_cena>
				</cena>							
			</cenas>
		</parte>
	</partes>


</guiao>

=== pralmeida/PDE-Trabalho1/SMALL.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="versao2.xsl"?>
<!DOCTYPE note SYSTEM "guiao.dtd">
<guiao>
	<cabecalho>
		<titulo>ABC</titulo>
		<autores>
			<autor>Autor 1</autor>
		</autores>
		<data_publicacao><ano>2013</ano><mes>03</mes><dia>12</dia></data_publicacao>
		<personagens>
		</personagens>
		<sinopse>Sinopse</sinopse>
	</cabecalho>
</guiao>

=== pralmeida/PDE-Trabalho1/Episodios_DTD.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="versao2.xsl"?>
<!DOCTYPE note SYSTEM "guiao.dtd">
<guiao>
	<cabecalho>
		<titulo>Título do Filme</titulo>
		<autores>
			<autor>Autor 1</autor>
			<autor>Autor 2</autor>		
		</autores>
		<data_publicacao><ano>2013</ano><mes>03</mes><dia>16</dia></data_publicacao>
		<personagens>
			<personagem id="p1">
				<nome>Personagem 1</nome>
				<descricao>Personagem 1. Declarada no cabeçalho.</descricao>
			</personagem>
			<personagem id="p2">
				<nome>Personagem 2</nome>
				<descricao>Personagem 2. Declarada no cabeçalho.</descricao>
			</personagem>
		</personagens>
		<sinopse>Sinopse do guião no cabeçalho.</sinopse>
	</cabecalho>
	<episodios>
		<episodio id="e1">
			<titulo>Episódio 1. Só com título</titulo>
			<personagens>
				<personagem id="p5">
					<nome>Personagem 5. Declarada na temporada 2</nome>
					<descricao>Descrição da personagem 5</descricao>
				</personagem>
			</personagens>
		</episodio>
		<episodio id="e2">
			<titulo>Episódio 2. Com partes</titulo>
			<partes>
				<parte id="parte1">
					<titulo>Primeira Parte. Só com título e sinopse.</titulo>
					<sinopse>Sinopse da parte 1 do episódio 2 da temporada 2.</sinopse>
				</parte>
				<parte id="parte2">
					<titulo>Primeira Parte. Com cenas.</titulo>
					<sinopse>Sinopse da parte 2 do episódio 2 da temporada 2.</sinopse>
					<personagens>
						<personagem id="p3">
							<nome>Personagem 3</nome>
							<descricao>Personagem 3. Declarada na parte 2.</descricao>
						</personagem>
					</personagens>
					<cenas>
						<cena contexto="Contexto da cena 1.">
						    <fala personagem="p1">Vou te matar!</fala>
						    Enquanto diz isto pega na <adereco>pistola</adereco> e dispara.
						    <fala personagem="p2">Ahh, mataste-me...</fala>
						    E cai morto no chão.
						    <fala personagem="p3">123</fala>
						</cena>
						<cena contexto = "Absolute bedlam. 300 drunken STOCKBROKERS, most in their early 20s">
						    <fala personagem="p1">Vou te matar, personagem 2!</fala>
						    Enquanto diz isto o <refere personagem="p1">personagem 1</refere> pega na <adereco>pistola</adereco> e dispara.
						    <fala personagem="p2">Ahh, mataste-me...</fala>
						    E o <refere personagem="p2">personagem 2</refere> cai morto no chão.
						</cena>							
					</cenas>
				</parte>
			</partes>
		</episodio>
		<episodio id="e3">
			<titulo>Episódio 2. Só com título</titulo>
			<personagens>
				<personagem id="p4">
					<nome>Personagem 4. Declarada num episódio</nome>
					<descricao>Personagem 4. Declarada num episódio</descricao>
				</personagem>
			
			</personagens>
			<!-- <temporada id="t98"><titulo>Temporada 98</titulo></temporada> -->
		</episodio>
	</episodios>
</guiao>

=== pralmeida/PDE-Trabalho1/Cenas_DTD.xml
<?xml version="1.0" encoding="UTF-8" ?>
<?xml-stylesheet type="text/xsl" href="versao2.xsl"?>
<!DOCTYPE note SYSTEM "guiao.dtd">
<guiao>
	<cabecalho>
		<titulo>Título do Filme</titulo>
		<autores>
			<autor>Autor 1</autor>
			<autor>Autor 2</autor>		
		</autores>
		<data_publicacao><ano>2013</ano><mes>03</mes><dia>12</dia></data_publicacao>
		<personagens>
			<personagem id="p1">
				<nome>Personagem 1</nome>
				<descricao>Personagem 1. Declarada no cabeçalho.</descricao>
			</personagem>
			<personagem id="p2">
				<nome>Personagem 2</nome>
				<descricao>Personagem 2. Declarada no cabeçalho.</descricao>
			</personagem>
			<personagem id="p3">
				<nome>Personagem 3</nome>
				<descricao>Personagem 3. Declarada no cabeçalho.</descricao>
			</personagem>
		</personagens>
		<sinopse>
			Sinopse do guião no cabeçalho.
			Sinopse do guião no cabeçalho.
			Sinopse do guião no cabeçalho. 
		</sinopse>
	</cabecalho>
	<cenas>
		<cena contexto="Contexto da cena 1.">
		    <fala personagem="p1">Vou te matar!</fala>
		    Enquanto diz isto pega na <adereco>pistola</adereco> e dispara.
		    <fala personagem="p2">Ahh, mataste-me...</fala>
		    E cai morto no chão.
		    <fala personagem="p3">123</fala>
		</cena>
		<cena contexto = "Absolute bedlam. 300 drunken STOCKBROKERS, most in their early 20s, ">
		    <fala personagem="p1">
		    	Vou te matar com a minha <adereco>pistola</adereco>, <refere personagem="p2">personagem 2</refere>!
		    	<comentario>
		    		O <refere personagem="p1">personagem 1</refere> está com cara de que está a falar mesmo a sério.
		    	</comentario>
		    </fala>
		    Enquanto diz isto o <refere personagem="p1">personagem 1</refere> pega na <adereco>pistola</adereco> e dispara.
	    	<comentario>
	    		Esta parte é em câmara lenta. 
	    		A bala parte da <adereco>pistola</adereco> e vai direitinha a caminho do coração do <refere personagem="p2">personagem 2</refere>
	    	</comentario>
		    <fala personagem="p2">Ahh, mataste-me...</fala>
		    E o <refere personagem="p2">personagem 2</refere> cai morto no chão.
		</cena>
	</cenas>
</guiao>

=== pralmeida/PDE-Trabalho1/wolf.xml
<?xml version="1.0"?>
<!DOCTYPE note SYSTEM "guiao.dtd">
<guiao>
	<cabecalho>
		<titulo>THE WOLF OF WALL STREET</titulo>
		<autor>Terence Winter</autor>
		<autor>Jordan Belfort</autor>
		<data_publicacao>
			<ano>2013</ano>
			<mes>03</mes>
			<dia>12</dia>
		</data_publicacao>
		<personagens>
			<personagem>
				<identificador>1</identificador>
				<nome>Jordan Belfort</nome>
				<descricao>
					Jordan Belfort is the son of Max and Leah Belfort of New York. In 1989, he and Daniel Porush founded the now defunct brokerage firm Stratton Oakmont which became the largest OTC firm in the United States at that time. Jordan and his business partner were charged with 10 counts of securities fraud and money laundering for the stock manipulation of at least 25 companies that Stratton had underwritten. After serving approximately 22 months in prison he was also ordered to return $100 million to former clients. He reportedly had been earning upwards to $50 million a year during his later years before the Department of Justice in the United States shut his operation down.
				</descricao>
			</personagem>
			<personagem>
				<identificador>2</identificador>
				<nome>Naomi Lapaglia</nome>
				<descricao>Naomi Lapaglia</descricao>
			</personagem>
			<personagem>
				<identificador>3</identificador>
				<nome>Donnie Azoff</nome>
				<descricao>Donnie Azoff</descricao>
			</personagem>
		</personagens>
		<sinopse>
			In 1987, Jordan Belfort (Leonardo DiCaprio) procures a job as a Wall Street stockbroker for L.F. Rothschild, employed under Mark Hanna (Matthew McConaughey), who quickly entices him with the sex and drugs-fueled stockbroker culture and teaches him that a stockbroker's only job is to make money for himself. Jordan soon finds his career terminated following Black Monday, and takes a job at a boiler room brokerage firm on Long Island that specializes in penny stocks. Thanks to his aggressive pitching style and the high commissions, Jordan makes a small fortune.
		</sinopse>
	</cabecalho>
	<cena>
		<identificador>1</identificador>
		<titulo>INSERT - TV COMMERCIAL - DAY</titulo>
		<contexto>
			Over jungle sound effects, the CAMERA is low, moving through brush from the POV of a stalking animal. As the brush parts, revealing Wall Street and the New York Stock Exchange, we HEAR the resonant voice of GENE HACKMAN.
		</contexto>
		<!-- GENE HACKMAN (V.O.) - The world of investing can be a jungle. (COMO REPRESENTAR UMA VOICE OVER? CONSIDERA-SE UMA FALA? 2 tipos de falas: locução ou diálogo?) -->
	</cena>
	<cena>
		<identificador>2</identificador>
		<titulo>INT. STRATTON OAKMONT III - BULLPEN - DAY (FEB ‘95)</titulo>
		<contexto>
			Absolute bedlam. 300 drunken STOCKBROKERS, most in their early 20s, chant wildly as JORDAN BELFORT, handsome, 30, stands beside a DWARF dressed in tights, cape &amp; helmet.
		</contexto>
	</cena>
</guiao>
